`--init_package` flag
addisonElliott/pyqt5ac pull request #29
Opened 2020-04-01 08:05 UTC by ZanSara

See #10. Add feature, tests and some documentation in README.md

2020-04-01 08:10 UTC, ZanSara commented
Having started from my previous PR branch, there are a lot of unrelated commits here. Please process #3 first.

2020-04-06 18:05 UTC, zkovari requested changes

2020-04-06 18:05 UTC, zkovari commented on README.md
> +* **init_package** - Specifies whether to check that the folder containing the generated files should also contain an `__init__.py` file. Default is True meaning the (empty) file will be added if mis
this is a bit difficult to understand. Could we simplify it something like "If specified, an empty `__init__.py` file is also generated in the output directory. Default value is True"

2020-04-06 18:05 UTC, zkovari commented on pyqt5ac.py
> +def main(rccOptions='', uicOptions='', force=False, initPackage=True, config='', ioPaths=(), variables=None):
why not to add the new argument to the end?

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +def _write_config_file_without_init(dir):
I think it's okay if you remove this and you rather use the initPackage argument in the main() method

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +def test_init_is_created(tmpdir):
you could remove this test case and rather extend the other valid generations (ui+resource) and assert there whether an extra __init__ file was created

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +    dest_file = tmpdir.join("generated/main_ui.py")
no need for this variable

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +    init_file = tmpdir.join("generated/__init__.py")
no need for this variable

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +    dest_file = tmpdir.join("generated/main_ui.py")
no need for this variable

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +    dest_file = tmpdir.join("generated/main_ui.py")
no need for this variable

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +    init_file = tmpdir.join("generated/__init__.py")
no need for this variable

2020-04-06 18:05 UTC, zkovari commented on tests/test_pyqt5ac.py
> +    _assert_path_exists(init_file)
you could also check that the content is empty

2020-04-06 18:05 UTC, zkovari commented on pyqt5ac.py
> +              help='Ensures that the folder containing the generated files is a Python submodule '
```suggestion
              help='Ensures that the folder containing the generated files is a Python subpackage '
```

no?

2020-04-06 18:05 UTC, zkovari commented on README.md
> +* **init_package** - Specifies whether to check that the folder containing the generated files should also contain an `__init__.py` file. Default is True meaning the (empty) file will be added if mis
or sth similar that you had on the cli

2020-04-06 18:05 UTC, zkovari commented
could you also resolve the conflict please?

2020-04-07 06:57 UTC, ZanSara commented on pyqt5ac.py
> +def main(rccOptions='', uicOptions='', force=False, initPackage=True, config='', ioPaths=(), variables=None):
For similarity to the `cli()` signature, where it had no default value. In Python args without default must come first. However, to the end it goes (with True as default in both signatures).

Side note: Click was setting the default anyway to `True` right before calling `cli()`, so it really makes no difference.

2020-05-09 12:13 UTC, zkovari commented on pyqt5ac.py
> +def main(rccOptions='', uicOptions='', force=False, initPackage=True, config='', ioPaths=(), variables=None):
I prefer it with default value.

The order does matter if someone is calling this main method with positional arguments. And people do that actually, I made a little code search on GitHub last time.

2020-05-09 12:25 UTC, zkovari approved these changes

2020-05-09 12:29 UTC, merged

2020-05-09 12:33 UTC, zkovari commented
@ZanSara thanks a lot!